direction: right

vars: {
  d2-config: {
    theme-id: 300
    layout-engine: elk
  }
}

classes: {
  pipeline register: {
    height: 500
    shape: rectangle
  }
}

# Pipeline registers
exmem: "EX/MEM" {
  class: pipeline register
}

memwb: "MEM/WB" {
  class: pipeline register
}

idex: "ID/EX" {
  class: pipeline register
}

ifid: "IF/ID" {
  class: pipeline register
}





# ###############################################################################
# P4
# ###############################################################################
exmem -> p4.memory: ctrl_p4.wren
exmem -> p4.memory: ctrl_p4.ren
exmem -> p4.memory: alu_out/addr
exmem -> p4.memory: rd_data2/wdata

p4 {
  memory: "main memory" {
    shape: rectangle
  }

}

p4.memory -> memwb: rdata
exmem -> memwb: insn_p4
exmem -> memwb: ctrl_p4

# ###############################################################################
# P5
# ###############################################################################

memwb -> p2.regfile: wr_data
