repos:
  # Baseline precommit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      - id: check-yaml
        args: ["--unsafe"]
  # Python linting and formatting through ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  # SystemVerilog linting with Verible
  - repo: local
    hooks:
      - id: verible-format
        name: Verible verilog format
        entry: verible-verilog-format
        language: system
        types_or: [verilog, system-verilog]
        args: [--flagfile, .rules.verible-format, --inplace]
