tests/tb/core_tb.sv
src/core.sv
src/alu.sv
src/aluctrl.sv
src/control.sv
src/insnmem.sv
src/memory.sv
src/regfile.sv
src/pipeline_regs/q1q2.sv
src/pipeline_regs/q2q3.sv
src/pipeline_regs/q3q4.sv
src/pipeline_regs/q4q5.sv
