name: CI jobs for chip simulation
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

env:
  OSS_CAD_SUITE_VERSION: "2025-08-31"
  OSS_CAD_SUITE_PATH: ${{ runner.temp }}/oss-cad-suite

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Cache OSS CAD Suite
        uses: actions/cache@v4
        id: oss-cad-cache
        with:
          path: ${{ env.OSS_CAD_SUITE_PATH }}
          key: oss-cad-suite-${{ runner.os }}-${{ env.OSS_CAD_SUITE_VERSION }}

      - name: Cache just
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/just
          key: just-${{ runner.os }}

      - name: Setup just
        if: steps.just-cache.outputs.cache-hit != 'true'
        uses: taiki-e/install-action@just

      - name: Setup OSS CAD Suite
        if: steps.oss-cad-cache.outputs.cache-hit != 'true'
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.OSS_CAD_SUITE_VERSION }}

      - name: Add OSS CAD Suite to path
        if: steps.oss-cad-cache.outputs.cache-hit != 'true'
        run: |
          echo ${{ env.OSS_CAD_SUITE_PATH }} >> "$GITHUB_PATH"

      - name: Run block tests
        run: |
          source sourceme
          cd $CPU_ROOT && just test
